# Fluent Bit as a DaemonSet for deployment.
{{- if .Values.fluentbit.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.fluentbit.name }}
  namespace: {{ include "aws-for-fluent-bit.namespace" . }}
  labels:
    k8s-app: {{ .Values.fluentbit.name }}
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Values.fluentbit.name }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.fluentbit.name }}
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: {{ .Values.fluentbit.name }}
        image: "{{ .Values.fluentbit.image.repository }}:{{ .Values.fluentbit.image.tag }}"
        imagePullPolicy: {{ .Values.fluentbit.image.pullPolicy }}
        env:
          - name: HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CI_VERSION
            value: "k8s/1.3.8"
        resources:
          {{- toYaml .Values.fluentbit.resources | nindent 10 }}
        volumeMounts:
          {{- toYaml .Values.fluentbit.volumeMounts | nindent 10 }}
      terminationGracePeriodSeconds: 10
      volumes:
        {{- toYaml .Values.fluentbit.volumes | nindent 8 }}
      serviceAccountName: fluent-bit
      tolerations:
        {{- toYaml .Values.fluentbit.tolerations | nindent 8 }}
{{- end }}
